name: Build and test python-jamf
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ '3.8', '3.9', '3.10', '3.11', '3.12', 'pypy-3.9', 'pypy-3.10' ]
    name: Build on ${{ matrix.os }} using ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
          pip install keyrings.alt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run Unit Tests
        run: |
          python -m unittest discover -s tests -p '*_test.py'
          #cp tests/test_records.py .
          #python test_records.py
        env:
          JAMF_HOSTNAME: ${{ secrets.JAMF_HOSTNAME }}
          JAMF_USERNAME: ${{ secrets.JAMF_USERNAME }}
          JAMF_PASSWORD: ${{ secrets.JAMF_PASSWORD }}
