name: pre-commit

on:
  pull_request_target:
    types: [opened, reopened]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Linting checks
        run: .github/workflows/pre-commit.sh
